apiVersion: v1
kind: Pod
metadata:
  labels:
    app: stressme
    app.kubernetes.io/name: stressme
  name: stressme
spec:
  runtimeClassName: nvidia
  containers:
  - args:
    - --cpu
    - "6"
    image: waggle/stressme:pr-6
    name: stressme
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: "3"
        memory: 1Gi
